# Generated by Django 4.2 on 2025-12-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='available_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
